apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - prometheus-configmap.yaml
  - prometheus-deployment.yaml
  - prometheus-service.yaml
  - grafana-configmap.yaml
  - grafana-deployment.yaml
  - grafana-service.yaml

configMapGenerator:
  - name: grafana-dashboard
    files:
      - antwort-overview.json=grafana-dashboard.json
    options:
      disableNameSuffixHash: true
