apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - backend-serviceaccount.yaml
  - backend-configmap.yaml
  - backend-deployment.yaml
  - backend-service.yaml
  - frontend-serviceaccount.yaml
  - frontend-configmap.yaml
  - frontend-deployment.yaml
  - frontend-service.yaml

commonLabels:
  app.kubernetes.io/part-of: antwort-responses-proxy
