apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - antwort-serviceaccount.yaml
  - antwort-configmap.yaml
  - antwort-deployment.yaml
  - antwort-service.yaml
  - sandbox-deployment.yaml
  - sandbox-service.yaml

commonLabels:
  app.kubernetes.io/part-of: antwort-code-interpreter
